import { AntdRegistry } from '@ant-design/nextjs-registry'
import type { Metadata } from 'next'
import localFont from 'next/font/local'
import { Providers } from './providers'

import './globals.css'

const geistSans = localFont({
  src: '../../public/fonts/Geist[wght].ttf',
  variable: '--font-geist-sans',
  display: 'swap',
})

const geistMono = localFont({
  src: '../../public/fonts/GeistMono[wght].ttf',
  variable: '--font-geist-mono',
  display: 'swap',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html
      lang="zh-CN"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Providers>
          <AntdRegistry>{children}</AntdRegistry>
        </Providers>
      </body>
    </html>
  )
}
